import Auto from "../models/Auto.model.js";

const autosData = [
  {
    marca: "Toyota",
    modelo: "Corolla",
    categoria: "sedan",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "gasolina",
    precioDia: 8500,
    disponible: true,
    ubicacion: "Buenos Aires",
    descripcion: "Sedan confiable y económico, ideal para la ciudad",
    caracteristicas: ["aire_acondicionado", "bluetooth", "gps"],
  },
  {
    marca: "Chevrolet",
    modelo: "Onix",
    categoria: "compacto",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "manual",
    combustible: "gasolina",
    precioDia: 6500,
    disponible: true,
    ubicacion: "Buenos Aires",
    descripcion: "Compacto económico perfecto para la ciudad",
    caracteristicas: ["aire_acondicionado", "bluetooth"],
  },
  {
    marca: "Ford",
    modelo: "Ranger",
    categoria: "suv",
    año: 2022,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "diesel",
    precioDia: 15000,
    disponible: true,
    ubicacion: "Mendoza",
    descripcion: "Camioneta 4x4 ideal para rutas de montaña",
    caracteristicas: ["aire_acondicionado", "4x4", "bluetooth", "gps"],
  },
  {
    marca: "Volkswagen",
    modelo: "Amarok",
    categoria: "suv",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "diesel",
    precioDia: 16000,
    disponible: true,
    ubicacion: "Bariloche",
    descripcion: "Potente pickup 4x4 para aventuras off-road",
    caracteristicas: ["aire_acondicionado", "4x4", "bluetooth", "gps", "cuero"],
  },
  {
    marca: "Peugeot",
    modelo: "208",
    categoria: "economico",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "manual",
    combustible: "gasolina",
    precioDia: 5500,
    disponible: true,
    ubicacion: "Córdoba",
    descripcion: "Auto económico y rendidor",
    caracteristicas: ["aire_acondicionado"],
  },
  {
    marca: "Fiat",
    modelo: "Cronos",
    categoria: "sedan",
    año: 2022,
    capacidadPasajeros: 5,
    transmision: "manual",
    combustible: "gasolina",
    precioDia: 7000,
    disponible: true,
    ubicacion: "Salta",
    descripcion: "Sedan espacioso y confortable",
    caracteristicas: ["aire_acondicionado", "bluetooth"],
  },
  {
    marca: "Mercedes-Benz",
    modelo: "Clase E",
    categoria: "lujo",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "gasolina",
    precioDia: 35000,
    disponible: true,
    ubicacion: "Buenos Aires",
    descripcion: "Sedan de lujo con todas las comodidades",
    caracteristicas: [
      "aire_acondicionado",
      "cuero",
      "gps",
      "bluetooth",
      "asientos_calefaccionados",
    ],
  },
  {
    marca: "BMW",
    modelo: "X5",
    categoria: "lujo",
    año: 2023,
    capacidadPasajeros: 7,
    transmision: "automatico",
    combustible: "gasolina",
    precioDia: 42000,
    disponible: true,
    ubicacion: "Buenos Aires",
    descripcion: "SUV de lujo con tecnología de punta",
    caracteristicas: [
      "aire_acondicionado",
      "cuero",
      "gps",
      "4x4",
      "bluetooth",
      "techo_panoramico",
    ],
  },
  {
    marca: "Renault",
    modelo: "Kangoo",
    categoria: "van",
    año: 2022,
    capacidadPasajeros: 7,
    transmision: "manual",
    combustible: "diesel",
    precioDia: 12000,
    disponible: true,
    ubicacion: "Mendoza",
    descripcion: "Van espaciosa para grupos familiares",
    caracteristicas: ["aire_acondicionado", "amplio_espacio"],
  },
  {
    marca: "Nissan",
    modelo: "Versa",
    categoria: "sedan",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "gasolina",
    precioDia: 8000,
    disponible: true,
    ubicacion: "Rosario",
    descripcion: "Sedan moderno y confortable",
    caracteristicas: ["aire_acondicionado", "bluetooth", "gps"],
  },
  {
    marca: "Hyundai",
    modelo: "Tucson",
    categoria: "suv",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "gasolina",
    precioDia: 14000,
    disponible: true,
    ubicacion: "Mar del Plata",
    descripcion: "SUV versátil para todo tipo de viajes",
    caracteristicas: [
      "aire_acondicionado",
      "bluetooth",
      "gps",
      "camara_retroceso",
    ],
  },
  {
    marca: "Citroën",
    modelo: "C3",
    categoria: "compacto",
    año: 2022,
    capacidadPasajeros: 5,
    transmision: "manual",
    combustible: "gasolina",
    precioDia: 6000,
    disponible: true,
    ubicacion: "Tucumán",
    descripcion: "Compacto ágil y económico",
    caracteristicas: ["aire_acondicionado"],
  },
  {
    marca: "Jeep",
    modelo: "Compass",
    categoria: "suv",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "automatico",
    combustible: "gasolina",
    precioDia: 17000,
    disponible: true,
    ubicacion: "Puerto Iguazú",
    descripcion: "SUV con capacidades off-road",
    caracteristicas: ["aire_acondicionado", "4x4", "bluetooth", "gps"],
  },
  {
    marca: "Volkswagen",
    modelo: "Polo",
    categoria: "compacto",
    año: 2023,
    capacidadPasajeros: 5,
    transmision: "manual",
    combustible: "gasolina",
    precioDia: 6800,
    disponible: true,
    ubicacion: "La Plata",
    descripcion: "Compacto confiable y rendidor",
    caracteristicas: ["aire_acondicionado", "bluetooth"],
  },
  {
    marca: "Ford",
    modelo: "Transit",
    categoria: "van",
    año: 2022,
    capacidadPasajeros: 15,
    transmision: "manual",
    combustible: "diesel",
    precioDia: 22000,
    disponible: true,
    ubicacion: "Buenos Aires",
    descripcion: "Van de gran capacidad para grupos grandes",
    caracteristicas: ["aire_acondicionado", "amplio_espacio", "bluetooth"],
  },
];

export const seedAutos = async () => {
  try {
    const count = await Auto.count();
    if (count > 0) {
      console.log("⏭️  Autos ya existen en la base de datos. Saltando...");
      return;
    }

    const autosWithPublisher = autosData.map((auto) => ({
      ...auto,
      published_by_user_id: 1,
    }));

    await Auto.bulkCreate(autosWithPublisher);
    console.log("✅ Autos creados exitosamente");
  } catch (error) {
    console.error("❌ Error al crear autos:", error.message);
    throw error;
  }
};
