import Circuito from "../models/Circuito.model.js";

const circuitosData = [
  {
    nombre: "Circuito Norte Argentino",
    descripcion:
      "Descubre Salta, Jujuy y Tucumán en un recorrido completo por el noroeste argentino",
    destinos: ["Salta", "Jujuy", "Tucumán", "Cafayate"],
    duracion: 12,
    precio: 185000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "guia",
      "entrada_parques",
    ],
    noIncluye: ["almuerzo", "cena", "bebidas"],
    itinerario: [
      "Día 1: Llegada a Salta",
      "Día 2: City tour Salta",
      "Día 3: Quebrada de Humahuaca",
      "Día 4: Salinas Grandes y Purmamarca",
      "Día 5: Cafayate y Valles Calchaquíes",
      "Día 6: Cachi",
      "Día 7-12: Continuación del circuito",
    ],
    fechaInicio: new Date("2026-04-10"),
    fechaFin: new Date("2026-04-22"),
    cupoMaximo: 25,
    cupoDisponible: 25,
    nivelDificultad: "moderado",
    disponible: true,
  },
  {
    nombre: "Circuito Patagonia Completa",
    descripcion:
      "Gran circuito recorriendo lo mejor de la Patagonia argentina y chilena",
    destinos: [
      "Bariloche",
      "El Calafate",
      "El Chaltén",
      "Ushuaia",
      "Puerto Madryn",
    ],
    duracion: 20,
    precio: 450000,
    incluye: [
      "hotel",
      "desayuno",
      "vuelos_internos",
      "traslados",
      "excursiones",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "entrada_parques"],
    itinerario: [
      "Días 1-4: Bariloche y lagos",
      "Días 5-8: El Calafate y glaciares",
      "Días 9-12: El Chaltén trekking",
      "Días 13-16: Ushuaia fin del mundo",
      "Días 17-20: Puerto Madryn avistajes",
    ],
    fechaInicio: new Date("2026-11-05"),
    fechaFin: new Date("2026-11-25"),
    cupoMaximo: 18,
    cupoDisponible: 18,
    nivelDificultad: "dificil",
    disponible: true,
  },
  {
    nombre: "Circuito Ruta del Vino",
    descripcion: "Recorrido enológico por Mendoza y San Juan",
    destinos: ["Mendoza", "Valle de Uco", "Maipú", "San Juan"],
    duracion: 8,
    precio: 125000,
    incluye: [
      "hotel",
      "desayuno",
      "tour_bodegas",
      "degustaciones",
      "traslados",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "compras_vino"],
    itinerario: [
      "Día 1: Llegada a Mendoza",
      "Día 2: Bodegas de Maipú",
      "Día 3: Valle de Uco",
      "Día 4: Alta montaña",
      "Día 5-8: San Juan y Valle de Tulum",
    ],
    fechaInicio: new Date("2026-03-15"),
    fechaFin: new Date("2026-03-23"),
    cupoMaximo: 20,
    cupoDisponible: 20,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Litoral Argentino",
    descripcion:
      "Descubre las maravillas del litoral: Iguazú, Iberá y Misiones",
    destinos: ["Puerto Iguazú", "Esteros del Iberá", "Posadas", "San Ignacio"],
    duracion: 10,
    precio: 165000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "entrada_parques",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena"],
    itinerario: [
      "Días 1-3: Cataratas del Iguazú",
      "Días 4-6: Esteros del Iberá",
      "Días 7-8: Ruinas Jesuíticas",
      "Días 9-10: Saltos del Moconá",
    ],
    fechaInicio: new Date("2026-06-01"),
    fechaFin: new Date("2026-06-11"),
    cupoMaximo: 22,
    cupoDisponible: 22,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Cuyo Completo",
    descripcion: "Recorre Mendoza, San Juan y San Luis en un circuito integral",
    destinos: ["Mendoza", "San Rafael", "San Juan", "San Luis"],
    duracion: 9,
    precio: 148000,
    incluye: ["hotel", "desayuno", "traslados", "excursiones", "guia"],
    noIncluye: ["almuerzo", "cena", "actividades_opcionales"],
    itinerario: [
      "Días 1-3: Mendoza y alta montaña",
      "Días 4-5: San Rafael y Atuel",
      "Días 6-7: San Juan e Ischigualasto",
      "Días 8-9: San Luis y sierras",
    ],
    fechaInicio: new Date("2026-05-10"),
    fechaFin: new Date("2026-05-19"),
    cupoMaximo: 20,
    cupoDisponible: 20,
    nivelDificultad: "moderado",
    disponible: true,
  },
  {
    nombre: "Circuito Península Valdés",
    descripcion:
      "Circuito especializado en avistaje de fauna marina en la Patagonia atlántica",
    destinos: ["Puerto Madryn", "Península Valdés", "Punta Tombo", "Gaiman"],
    duracion: 6,
    precio: 112000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "avistajes",
      "entrada_reservas",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "navegaciones_opcionales"],
    itinerario: [
      "Día 1: Llegada Puerto Madryn",
      "Día 2: Península Valdés completa",
      "Día 3: Avistaje de ballenas",
      "Día 4: Punta Tombo pingüinera",
      "Día 5-6: Gaiman y regreso",
    ],
    fechaInicio: new Date("2026-09-15"),
    fechaFin: new Date("2026-09-21"),
    cupoMaximo: 16,
    cupoDisponible: 16,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Sierras de Córdoba",
    descripcion: "Descubre las sierras cordobesas y sus pueblos pintorescos",
    destinos: [
      "Córdoba Capital",
      "Villa Carlos Paz",
      "La Cumbrecita",
      "Capilla del Monte",
    ],
    duracion: 7,
    precio: 95000,
    incluye: ["hotel", "desayuno", "traslados", "excursiones", "guia"],
    noIncluye: ["almuerzo", "cena", "actividades_opcionales"],
    itinerario: [
      "Día 1: City tour Córdoba",
      "Día 2-3: Villa Carlos Paz",
      "Día 4-5: La Cumbrecita",
      "Día 6-7: Capilla del Monte",
    ],
    fechaInicio: new Date("2026-03-20"),
    fechaFin: new Date("2026-03-27"),
    cupoMaximo: 25,
    cupoDisponible: 25,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Lagos Andinos",
    descripcion: "Cruce de lagos entre Argentina y Chile por la cordillera",
    destinos: [
      "Bariloche",
      "Villa La Angostura",
      "Puerto Varas",
      "Puerto Montt",
    ],
    duracion: 8,
    precio: 195000,
    incluye: [
      "hotel",
      "desayuno",
      "cruce_lagos",
      "traslados",
      "excursiones",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "migraciones"],
    itinerario: [
      "Días 1-3: Bariloche",
      "Día 4: Villa La Angostura",
      "Día 5: Cruce de lagos",
      "Días 6-8: Chile - Puerto Varas",
    ],
    fechaInicio: new Date("2026-02-10"),
    fechaFin: new Date("2026-02-18"),
    cupoMaximo: 20,
    cupoDisponible: 20,
    nivelDificultad: "moderado",
    disponible: true,
  },
  {
    nombre: "Circuito Cataratas Completo",
    descripcion: "Visita las Cataratas del Iguazú desde ambos lados",
    destinos: ["Puerto Iguazú", "Foz do Iguaçu", "Ciudad del Este"],
    duracion: 5,
    precio: 88000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "entrada_parques",
      "excursiones",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "compras"],
    itinerario: [
      "Día 1: Llegada",
      "Día 2: Lado argentino",
      "Día 3: Lado brasileño",
      "Día 4: Ciudad del Este shopping",
      "Día 5: Regreso",
    ],
    fechaInicio: new Date("2026-07-05"),
    fechaFin: new Date("2026-07-10"),
    cupoMaximo: 30,
    cupoDisponible: 30,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Ruta 40",
    descripcion: "Aventura épica recorriendo la mítica Ruta 40",
    destinos: [
      "Mendoza",
      "Malargüe",
      "Bariloche",
      "El Bolsón",
      "Esquel",
      "El Calafate",
    ],
    duracion: 18,
    precio: 385000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "vehiculo_4x4",
      "guia",
      "excursiones",
    ],
    noIncluye: ["almuerzo", "cena", "combustible"],
    itinerario: [
      "Días 1-3: Mendoza",
      "Días 4-6: Malargüe y sur mendocino",
      "Días 7-10: Bariloche y región",
      "Días 11-13: El Bolsón y Esquel",
      "Días 14-18: Ruta a El Calafate",
    ],
    fechaInicio: new Date("2026-10-15"),
    fechaFin: new Date("2026-11-02"),
    cupoMaximo: 12,
    cupoDisponible: 12,
    nivelDificultad: "dificil",
    disponible: true,
  },
  {
    nombre: "Circuito Tucumán Colonial",
    descripcion: "Historia y naturaleza en la cuna de la independencia",
    destinos: [
      "San Miguel de Tucumán",
      "Tafí del Valle",
      "Cafayate",
      "Quilmes",
    ],
    duracion: 6,
    precio: 78000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "guia",
      "entradas",
    ],
    noIncluye: ["almuerzo", "cena"],
    itinerario: [
      "Día 1: City tour histórico",
      "Día 2-3: Tafí del Valle",
      "Día 4-5: Cafayate y bodegas",
      "Día 6: Ruinas de Quilmes",
    ],
    fechaInicio: new Date("2026-07-09"),
    fechaFin: new Date("2026-07-15"),
    cupoMaximo: 20,
    cupoDisponible: 20,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Tierra del Fuego",
    descripcion: "Explora el fin del mundo en un circuito completo",
    destinos: ["Ushuaia", "Parque Nacional", "Harberton", "Tolhuin"],
    duracion: 5,
    precio: 135000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "navegacion_beagle",
      "excursiones",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "entrada_parque"],
    itinerario: [
      "Día 1: Llegada y city tour",
      "Día 2: Navegación Beagle",
      "Día 3: Parque Nacional",
      "Día 4: Lagos fueguinos",
      "Día 5: Regreso",
    ],
    fechaInicio: new Date("2026-12-10"),
    fechaFin: new Date("2026-12-15"),
    cupoMaximo: 18,
    cupoDisponible: 18,
    nivelDificultad: "moderado",
    disponible: true,
  },
  {
    nombre: "Circuito Glaciares Patagónicos",
    descripcion: "Circuito especializado en glaciares de la Patagonia",
    destinos: ["El Calafate", "El Chaltén", "Perito Moreno", "Upsala"],
    duracion: 8,
    precio: 215000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "navegaciones",
      "trekking_glaciar",
      "guia",
    ],
    noIncluye: ["almuerzo", "cena", "equipo_trekking"],
    itinerario: [
      "Días 1-2: El Calafate",
      "Día 3: Glaciar Perito Moreno",
      "Día 4: Mini trekking sobre hielo",
      "Días 5-8: El Chaltén trekking",
    ],
    fechaInicio: new Date("2026-11-20"),
    fechaFin: new Date("2026-11-28"),
    cupoMaximo: 15,
    cupoDisponible: 15,
    nivelDificultad: "dificil",
    disponible: true,
  },
  {
    nombre: "Circuito Entre Ríos Termal",
    descripcion: "Relax y naturaleza en las termas de Entre Ríos",
    destinos: ["Colón", "Concepción del Uruguay", "Federación", "Chajarí"],
    duracion: 6,
    precio: 68000,
    incluye: ["hotel_termal", "desayuno", "acceso_termas", "traslados"],
    noIncluye: ["almuerzo", "cena", "masajes"],
    itinerario: [
      "Días 1-2: Termas de Colón",
      "Día 3: Concepción del Uruguay",
      "Días 4-5: Federación termas",
      "Día 6: Chajarí y regreso",
    ],
    fechaInicio: new Date("2026-08-15"),
    fechaFin: new Date("2026-08-21"),
    cupoMaximo: 25,
    cupoDisponible: 25,
    nivelDificultad: "facil",
    disponible: true,
  },
  {
    nombre: "Circuito Costa Atlántica",
    descripcion: "Recorre las mejores playas de la costa argentina",
    destinos: ["Mar del Plata", "Villa Gesell", "Pinamar", "Mar de las Pampas"],
    duracion: 7,
    precio: 92000,
    incluye: ["hotel", "desayuno", "traslados"],
    noIncluye: ["almuerzo", "cena", "actividades_playa"],
    itinerario: [
      "Días 1-2: Mar del Plata",
      "Días 3-4: Villa Gesell",
      "Días 5-6: Pinamar y Mar de las Pampas",
      "Día 7: Regreso",
    ],
    fechaInicio: new Date("2026-01-10"),
    fechaFin: new Date("2026-01-17"),
    cupoMaximo: 30,
    cupoDisponible: 30,
    nivelDificultad: "facil",
    disponible: true,
  },
];

export const seedCircuitos = async () => {
  try {
    const count = await Circuito.count();
    if (count > 0) {
      console.log("⏭️  Circuitos ya existen en la base de datos. Saltando...");
      return;
    }

    await Circuito.bulkCreate(circuitosData);
    console.log("✅ Circuitos creados exitosamente");
  } catch (error) {
    console.error("❌ Error al crear circuitos:", error.message);
    throw error;
  }
};
