import Crucero from "../models/Crucero.model.js";

const crucerosData = [
  {
    nombre: "Crucero Caribe Tropical",
    naviera: "Royal Caribbean",
    barco: "Symphony of the Seas",
    descripcion:
      "Crucero de lujo por el Caribe visitando las mejores playas e islas",
    itinerario: ["Miami", "Cozumel", "Roatán", "Costa Maya", "Nassau", "Miami"],
    duracion: 7,
    fechaSalida: new Date("2026-03-15"),
    fechaRegreso: new Date("2026-03-22"),
    puertoSalida: "Miami, Florida",
    puertoLlegada: "Miami, Florida",
    precioDesde: 850000,
    tiposCabina: [
      { tipo: "interior", precio: 850000 },
      { tipo: "oceanview", precio: 1100000 },
      { tipo: "balcon", precio: 1450000 },
      { tipo: "suite", precio: 2500000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "entretenimiento",
      "gimnasio",
      "piscinas",
    ],
    noIncluye: ["bebidas_alcoholicas", "excursiones", "propinas", "wifi"],
    serviciosABordo: ["restaurantes", "piscinas", "teatro", "casino", "spa"],
    capacidadTotal: 3000,
    cabinasDisponibles: 3000,
  },
  {
    nombre: "Crucero Mediterráneo Mágico",
    naviera: "MSC Cruises",
    barco: "MSC Divina",
    descripcion: "Recorre las joyas del Mediterráneo en 10 días inolvidables",
    itinerario: [
      "Barcelona",
      "Marsella",
      "Génova",
      "Roma",
      "Nápoles",
      "Palermo",
      "Valencia",
      "Barcelona",
    ],
    duracion: 10,
    fechaSalida: new Date("2026-05-20"),
    fechaRegreso: new Date("2026-05-30"),
    puertoSalida: "Barcelona, España",
    puertoLlegada: "Barcelona, España",
    precioDesde: 1200000,
    tiposCabina: [
      { tipo: "interior", precio: 1200000 },
      { tipo: "oceanview", precio: 1550000 },
      { tipo: "balcon", precio: 1950000 },
      { tipo: "suite", precio: 3200000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "entretenimiento",
      "gimnasio",
      "piscinas",
      "spa_termal",
    ],
    noIncluye: ["bebidas_premium", "excursiones", "propinas", "casino"],
    serviciosABordo: ["restaurantes", "piscinas", "spa_termal", "teatro"],
    capacidadTotal: 2500,
    cabinasDisponibles: 2500,
  },
  {
    nombre: "Crucero Alaska Glaciares",
    naviera: "Norwegian Cruise Line",
    barco: "Norwegian Bliss",
    descripcion:
      "Aventura por los impresionantes glaciares y fiordos de Alaska",
    itinerario: [
      "Seattle",
      "Juneau",
      "Skagway",
      "Glacier Bay",
      "Ketchikan",
      "Victoria",
      "Seattle",
    ],
    duracion: 7,
    fechaSalida: new Date("2026-07-10"),
    fechaRegreso: new Date("2026-07-17"),
    puertoSalida: "Seattle, Washington",
    puertoLlegada: "Seattle, Washington",
    precioDesde: 1350000,
    tiposCabina: [
      { tipo: "interior", precio: 1350000 },
      { tipo: "oceanview", precio: 1650000 },
      { tipo: "balcon", precio: 2100000 },
      { tipo: "suite", precio: 3500000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "entretenimiento",
      "gimnasio",
      "pista_karting",
    ],
    noIncluye: ["bebidas_alcoholicas", "excursiones", "propinas"],
    serviciosABordo: ["restaurantes", "pista_karting", "teatro", "spa"],
    capacidadTotal: 2000,
    cabinasDisponibles: 2000,
  },
  {
    nombre: "Crucero Fjordos Noruegos",
    naviera: "Costa Cruises",
    barco: "Costa Favolosa",
    descripcion: "Explora los majestuosos fiordos del norte de Europa",
    itinerario: [
      "Copenhague",
      "Geiranger",
      "Bergen",
      "Flam",
      "Stavanger",
      "Oslo",
      "Copenhague",
    ],
    duracion: 8,
    fechaSalida: new Date("2026-06-15"),
    fechaRegreso: new Date("2026-06-23"),
    puertoSalida: "Copenhague, Dinamarca",
    puertoLlegada: "Copenhague, Dinamarca",
    precioDesde: 1450000,
    tiposCabina: [
      { tipo: "interior", precio: 1450000 },
      { tipo: "oceanview", precio: 1800000 },
      { tipo: "balcon", precio: 2250000 },
      { tipo: "suite", precio: 3800000 },
    ],
    incluye: ["alojamiento", "comidas", "entretenimiento", "gimnasio"],
    noIncluye: ["bebidas", "excursiones", "propinas", "wifi"],
    serviciosABordo: ["restaurantes", "spa", "biblioteca"],
    capacidadTotal: 1800,
    cabinasDisponibles: 1800,
  },
  {
    nombre: "Crucero Islas Griegas",
    naviera: "Celestyal Cruises",
    barco: "Celestyal Olympia",
    descripcion: "Descubre las islas griegas en un crucero boutique",
    itinerario: [
      "Atenas",
      "Mykonos",
      "Kusadasi",
      "Patmos",
      "Creta",
      "Santorini",
      "Atenas",
    ],
    duracion: 7,
    fechaSalida: new Date("2026-08-01"),
    fechaRegreso: new Date("2026-08-08"),
    puertoSalida: "Pireo, Atenas",
    puertoLlegada: "Pireo, Atenas",
    precioDesde: 980000,
    tiposCabina: [
      { tipo: "interior", precio: 980000 },
      { tipo: "oceanview", precio: 1250000 },
      { tipo: "balcon", precio: 1650000 },
      { tipo: "suite", precio: 2800000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "bebidas_seleccionadas",
      "excursiones",
      "propinas",
    ],
    noIncluye: ["bebidas_premium", "spa"],
    serviciosABordo: ["restaurantes", "piscinas", "entretenimiento_diario"],
    capacidadTotal: 1200,
    cabinasDisponibles: 1200,
  },
  {
    nombre: "Crucero Patagonia y Cabo de Hornos",
    naviera: "Australis",
    barco: "Stella Australis",
    descripcion:
      "Expedición única navegando el extremo sur de América hasta el Cabo de Hornos",
    itinerario: [
      "Punta Arenas",
      "Bahía Ainsworth",
      "Isla Tucker",
      "Cabo de Hornos",
      "Bahía Wulaia",
      "Ushuaia",
    ],
    duracion: 4,
    fechaSalida: new Date("2026-11-10"),
    fechaRegreso: new Date("2026-11-14"),
    puertoSalida: "Punta Arenas, Chile",
    puertoLlegada: "Ushuaia, Argentina",
    precioDesde: 650000,
    tiposCabina: [
      { tipo: "standard", precio: 650000 },
      { tipo: "superior", precio: 850000 },
      { tipo: "suite", precio: 1200000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "bebidas",
      "excursiones",
      "conferencias",
    ],
    noIncluye: ["propinas", "transfer"],
    serviciosABordo: ["restaurante", "bar", "sala_conferencias"],
    capacidadTotal: 150,
    cabinasDisponibles: 150,
  },
  {
    nombre: "Crucero Trasatlántico",
    naviera: "Cunard Line",
    barco: "Queen Mary 2",
    descripcion: "Travesía clásica cruzando el Atlántico en estilo legendario",
    itinerario: ["Southampton", "En_el_mar", "Nueva_York"],
    duracion: 7,
    fechaSalida: new Date("2026-09-05"),
    fechaRegreso: new Date("2026-09-12"),
    puertoSalida: "Southampton, Inglaterra",
    puertoLlegada: "Nueva York, USA",
    precioDesde: 1550000,
    tiposCabina: [
      { tipo: "interior", precio: 1550000 },
      { tipo: "oceanview", precio: 2100000 },
      { tipo: "balcon", precio: 2800000 },
      { tipo: "suite", precio: 5500000 },
    ],
    incluye: [
      "alojamiento",
      "comidas_gourmet",
      "entretenimiento",
      "planetario",
      "biblioteca",
    ],
    noIncluye: ["bebidas_alcoholicas", "propinas", "spa"],
    serviciosABordo: [
      "restaurantes_gourmet",
      "planetario",
      "biblioteca",
      "teatro",
    ],
    capacidadTotal: 2500,
    cabinasDisponibles: 2500,
  },
  {
    nombre: "Crucero Río Danubio",
    naviera: "Viking River Cruises",
    barco: "Viking Baldur",
    descripcion:
      "Navegación cultural por el Danubio visitando capitales europeas",
    itinerario: [
      "Budapest",
      "Viena",
      "Bratislava",
      "Linz",
      "Passau",
      "Regensburg",
      "Nuremberg",
    ],
    duracion: 8,
    fechaSalida: new Date("2026-05-01"),
    fechaRegreso: new Date("2026-05-09"),
    puertoSalida: "Budapest, Hungría",
    puertoLlegada: "Nuremberg, Alemania",
    precioDesde: 1850000,
    tiposCabina: [
      { tipo: "standard", precio: 1850000 },
      { tipo: "balcon_frances", precio: 2350000 },
      { tipo: "suite", precio: 3500000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "bebidas_ilimitadas",
      "excursiones",
      "wifi",
    ],
    noIncluye: ["propinas", "spa"],
    serviciosABordo: ["restaurantes", "salon_panoramico", "biblioteca", "spa"],
    capacidadTotal: 180,
    cabinasDisponibles: 180,
  },
  {
    nombre: "Crucero Caribe Sur",
    naviera: "Princess Cruises",
    barco: "Caribbean Princess",
    descripcion: "Explora las islas menos visitadas del Caribe Sur",
    itinerario: [
      "San_Juan",
      "St_Thomas",
      "Barbados",
      "Santa_Lucia",
      "Antigua",
      "St_Maarten",
      "San_Juan",
    ],
    duracion: 7,
    fechaSalida: new Date("2026-02-20"),
    fechaRegreso: new Date("2026-02-27"),
    puertoSalida: "San Juan, Puerto Rico",
    puertoLlegada: "San Juan, Puerto Rico",
    precioDesde: 920000,
    tiposCabina: [
      { tipo: "interior", precio: 920000 },
      { tipo: "oceanview", precio: 1200000 },
      { tipo: "balcon", precio: 1550000 },
      { tipo: "mini_suite", precio: 2200000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "entretenimiento",
      "movies_under_stars",
    ],
    noIncluye: ["bebidas_alcoholicas", "excursiones", "propinas", "casino"],
    serviciosABordo: ["restaurantes", "movies_under_stars", "casino", "spa"],
    capacidadTotal: 2800,
    cabinasDisponibles: 2800,
  },
  {
    nombre: "Crucero Ártico Exploratorio",
    naviera: "Hurtigruten",
    barco: "MS Fram",
    descripcion:
      "Expedición al Ártico para observar auroras boreales y naturaleza extrema",
    itinerario: [
      "Tromsø",
      "Honningsvåg",
      "Svalbard",
      "Ny_Alesund",
      "Longyearbyen",
    ],
    duracion: 6,
    fechaSalida: new Date("2026-10-15"),
    fechaRegreso: new Date("2026-10-21"),
    puertoSalida: "Tromsø, Noruega",
    puertoLlegada: "Longyearbyen, Svalbard",
    precioDesde: 2200000,
    tiposCabina: [
      { tipo: "interior", precio: 2200000 },
      { tipo: "oceanview", precio: 2800000 },
      { tipo: "suite", precio: 4500000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "excursiones_expedicion",
      "conferencias",
      "equipo_artico",
    ],
    noIncluye: ["bebidas_alcoholicas", "propinas"],
    serviciosABordo: [
      "restaurante",
      "observatorio",
      "conferencias_naturalistas",
    ],
    capacidadTotal: 300,
    cabinasDisponibles: 300,
  },
  {
    nombre: "Crucero Canales Patagónicos",
    naviera: "Skorpios",
    barco: "Skorpios III",
    descripcion:
      "Navegación por los prístinos canales chilenos de la Patagonia",
    itinerario: [
      "Puerto_Montt",
      "Golfo_Corcovado",
      "Parque_Pumalín",
      "Glaciar_Pío_XI",
      "Puerto_Natales",
    ],
    duracion: 6,
    fechaSalida: new Date("2026-12-01"),
    fechaRegreso: new Date("2026-12-07"),
    puertoSalida: "Puerto Montt, Chile",
    puertoLlegada: "Puerto Natales, Chile",
    precioDesde: 1150000,
    tiposCabina: [
      { tipo: "standard", precio: 1150000 },
      { tipo: "superior", precio: 1550000 },
      { tipo: "suite", precio: 2200000 },
    ],
    incluye: ["alojamiento", "comidas", "bebidas", "excursiones", "kayak"],
    noIncluye: ["propinas", "transfer"],
    serviciosABordo: ["restaurante", "bar", "salon_panoramico"],
    capacidadTotal: 120,
    cabinasDisponibles: 120,
  },
  {
    nombre: "Crucero Asia Exótica",
    naviera: "Celebrity Cruises",
    barco: "Celebrity Millennium",
    descripcion: "Viaje por los destinos más exóticos del Sudeste Asiático",
    itinerario: [
      "Singapur",
      "Bangkok",
      "Ho_Chi_Minh",
      "Hong_Kong",
      "Taipei",
      "Tokio",
    ],
    duracion: 14,
    fechaSalida: new Date("2026-04-10"),
    fechaRegreso: new Date("2026-04-24"),
    puertoSalida: "Singapur",
    puertoLlegada: "Tokio, Japón",
    precioDesde: 2450000,
    tiposCabina: [
      { tipo: "interior", precio: 2450000 },
      { tipo: "oceanview", precio: 3100000 },
      { tipo: "balcon", precio: 3900000 },
      { tipo: "suite", precio: 6500000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "entretenimiento",
      "lawn_club",
      "spa_acceso",
    ],
    noIncluye: ["bebidas_premium", "excursiones", "propinas", "wifi"],
    serviciosABordo: ["restaurantes", "lawn_club", "spa_acceso", "teatro"],
    capacidadTotal: 2000,
    cabinasDisponibles: 2000,
  },
  {
    nombre: "Crucero Hawái Paradisíaco",
    naviera: "Norwegian Cruise Line",
    barco: "Pride of America",
    descripcion: "Descubre las islas de Hawái en un crucero dedicado",
    itinerario: ["Honolulu", "Maui", "Hilo", "Kona", "Kauai", "Honolulu"],
    duracion: 7,
    fechaSalida: new Date("2026-08-15"),
    fechaRegreso: new Date("2026-08-22"),
    puertoSalida: "Honolulu, Oahu",
    puertoLlegada: "Honolulu, Oahu",
    precioDesde: 1850000,
    tiposCabina: [
      { tipo: "interior", precio: 1850000 },
      { tipo: "oceanview", precio: 2350000 },
      { tipo: "balcon", precio: 2950000 },
      { tipo: "suite", precio: 4800000 },
    ],
    incluye: ["alojamiento", "comidas", "entretenimiento", "pernocte_puertos"],
    noIncluye: ["bebidas_alcoholicas", "excursiones", "propinas"],
    serviciosABordo: ["restaurantes", "piscinas", "entretenimiento"],
    capacidadTotal: 1900,
    cabinasDisponibles: 1900,
  },
  {
    nombre: "Crucero Amazonas Exploratorio",
    naviera: "Aqua Expeditions",
    barco: "Aqua Nera",
    descripcion: "Expedición de lujo por el río Amazonas peruano",
    itinerario: [
      "Iquitos",
      "Reserva_Pacaya_Samiria",
      "Nauta_Caño",
      "Río_Ucayali",
      "Iquitos",
    ],
    duracion: 4,
    fechaSalida: new Date("2026-07-20"),
    fechaRegreso: new Date("2026-07-24"),
    puertoSalida: "Iquitos, Perú",
    puertoLlegada: "Iquitos, Perú",
    precioDesde: 1550000,
    tiposCabina: [
      { tipo: "design_suite", precio: 1550000 },
      { tipo: "luxury_suite", precio: 2100000 },
      { tipo: "master_suite", precio: 3200000 },
    ],
    incluye: [
      "alojamiento",
      "comidas_gourmet",
      "bebidas",
      "excursiones",
      "kayak",
      "guias_naturalistas",
    ],
    noIncluye: ["propinas", "vuelos"],
    serviciosABordo: ["restaurante_gourmet", "bar", "spa_boutique"],
    capacidadTotal: 40,
    cabinasDisponibles: 40,
  },
  {
    nombre: "Crucero Antártida Expedición",
    naviera: "Quark Expeditions",
    barco: "Ocean Endeavour",
    descripcion: "Aventura extrema al continente blanco",
    itinerario: [
      "Ushuaia",
      "Drake_Passage",
      "Península_Antártica",
      "Islas_Shetland_del_Sur",
      "Drake_Passage",
      "Ushuaia",
    ],
    duracion: 10,
    fechaSalida: new Date("2026-12-20"),
    fechaRegreso: new Date("2026-12-30"),
    puertoSalida: "Ushuaia, Argentina",
    puertoLlegada: "Ushuaia, Argentina",
    precioDesde: 5500000,
    tiposCabina: [
      { tipo: "triple", precio: 5500000 },
      { tipo: "twin", precio: 6800000 },
      { tipo: "superior", precio: 8500000 },
      { tipo: "suite", precio: 12000000 },
    ],
    incluye: [
      "alojamiento",
      "comidas",
      "bebidas",
      "excursiones_zodiac",
      "conferencias",
      "parka_regalo",
    ],
    noIncluye: ["vuelos", "propinas", "equipo_personal"],
    serviciosABordo: [
      "restaurante",
      "conferencias",
      "biblioteca",
      "observatorio",
    ],
    capacidadTotal: 180,
    cabinasDisponibles: 180,
  },
];

export const seedCruceros = async () => {
  try {
    const count = await Crucero.count();
    if (count > 0) {
      console.log("⏭️  Cruceros ya existen en la base de datos. Saltando...");
      return;
    }

    const crucerosWithPublisher = crucerosData.map((crucero) => ({
      ...crucero,
      published_by_user_id: 1,
      mesSalida: crucero.fechaSalida.getMonth() + 1, // 1-12
      duracionDias: crucero.duracion + 1, // días = noches + 1
      importeAdulto: crucero.precioDesde,
      importeMenor: crucero.precioDesde * 0.5, // 50% descuento para menores
    }));

    await Crucero.bulkCreate(crucerosWithPublisher);
    console.log("✅ Cruceros creados exitosamente");
  } catch (error) {
    console.error("❌ Error al crear cruceros:", error.message);
    throw error;
  }
};
