import Paquete from "../models/Paquete.model.js";

const paquetesData = [
  {
    nombre: "Buenos Aires Clásico",
    descripcion:
      "Descubre los lugares más emblemáticos de Buenos Aires en 4 días",
    destino: "Buenos Aires",
    duracion: 4,
    noches: 3,
    precio: 45000,
    cupoMaximo: 20,
    cupoDisponible: 20,
    incluye: ["hotel", "desayuno", "city_tour", "show_tango"],
    noIncluye: ["almuerzo", "cena", "traslados_aeropuerto"],
    fechaInicio: new Date("2026-02-01"),
    fechaFin: new Date("2026-02-04"),
    activo: true,
  },
  {
    nombre: "Patagonia Aventura",
    descripcion: "Aventura completa por la Patagonia argentina",
    destino: "Patagonia",
    duracion: 10,
    noches: 9,
    precio: 180000,
    cupoMaximo: 15,
    cupoDisponible: 15,
    incluye: [
      "hotel",
      "desayuno",
      "excursion_glaciar",
      "trekking",
      "traslados",
    ],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-03-10"),
    fechaFin: new Date("2026-03-19"),
    activo: true,
  },
  {
    nombre: "Cataratas del Iguazú",
    descripcion: "Explora las majestuosas Cataratas del Iguazú",
    destino: "Puerto Iguazú",
    duracion: 3,
    noches: 2,
    precio: 65000,
    cupoMaximo: 25,
    cupoDisponible: 25,
    incluye: [
      "hotel",
      "desayuno",
      "entrada_parque",
      "excursion_lado_brasileño",
    ],
    noIncluye: ["almuerzo", "cena", "traslados_aeropuerto"],
    fechaInicio: new Date("2026-02-15"),
    fechaFin: new Date("2026-02-17"),
    activo: true,
  },
  {
    nombre: "Mendoza Vinos",
    descripcion: "Tour enológico por las mejores bodegas de Mendoza",
    destino: "Mendoza",
    duracion: 5,
    noches: 4,
    precio: 75000,
    cupoMaximo: 18,
    cupoDisponible: 18,
    incluye: [
      "hotel",
      "desayuno",
      "tour_bodegas",
      "degustaciones",
      "traslados",
    ],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-04-01"),
    fechaFin: new Date("2026-04-05"),
    activo: true,
  },
  {
    nombre: "Salta y Jujuy",
    descripcion: "Recorre los paisajes del noroeste argentino",
    destino: "Salta",
    duracion: 7,
    noches: 6,
    precio: 95000,
    cupoMaximo: 20,
    cupoDisponible: 20,
    incluye: [
      "hotel",
      "desayuno",
      "tour_quebrada_humahuaca",
      "salinas_grandes",
      "traslados",
    ],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-05-10"),
    fechaFin: new Date("2026-05-16"),
    activo: true,
  },
  {
    nombre: "Bariloche Ski",
    descripcion: "Disfruta de la nieve en Bariloche",
    destino: "San Carlos de Bariloche",
    duracion: 6,
    noches: 5,
    precio: 120000,
    cupoMaximo: 15,
    cupoDisponible: 15,
    incluye: ["hotel", "desayuno", "pase_ski", "clases_ski", "traslados"],
    noIncluye: ["almuerzo", "cena", "equipo_ski"],
    fechaInicio: new Date("2026-07-15"),
    fechaFin: new Date("2026-07-20"),
    activo: true,
  },
  {
    nombre: "Córdoba Sierras",
    descripcion: "Naturaleza y aventura en las sierras de Córdoba",
    destino: "Córdoba",
    duracion: 4,
    noches: 3,
    precio: 55000,
    cupoMaximo: 22,
    cupoDisponible: 22,
    incluye: ["hotel", "desayuno", "trekking", "visita_capilla_del_monte"],
    noIncluye: ["almuerzo", "cena", "traslados_aeropuerto"],
    fechaInicio: new Date("2026-03-20"),
    fechaFin: new Date("2026-03-23"),
    activo: true,
  },
  {
    nombre: "Ushuaia Fin del Mundo",
    descripcion: "Viaja al fin del mundo en Ushuaia",
    destino: "Ushuaia",
    duracion: 5,
    noches: 4,
    precio: 150000,
    cupoMaximo: 12,
    cupoDisponible: 12,
    incluye: [
      "hotel",
      "desayuno",
      "navegacion_beagle",
      "parque_nacional",
      "traslados",
    ],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-06-01"),
    fechaFin: new Date("2026-06-05"),
    activo: true,
  },
  {
    nombre: "Peninsula Valdés",
    descripcion: "Observa ballenas y fauna marina en Puerto Madryn",
    destino: "Puerto Madryn",
    duracion: 4,
    noches: 3,
    precio: 85000,
    cupoMaximo: 18,
    cupoDisponible: 18,
    incluye: [
      "hotel",
      "desayuno",
      "avistaje_ballenas",
      "pinguinera",
      "traslados",
    ],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-09-15"),
    fechaFin: new Date("2026-09-18"),
    activo: true,
  },
  {
    nombre: "Tucumán Colonial",
    descripcion: "Historia y cultura en la cuna de la independencia",
    destino: "San Miguel de Tucumán",
    duracion: 3,
    noches: 2,
    precio: 42000,
    cupoMaximo: 20,
    cupoDisponible: 20,
    incluye: ["hotel", "desayuno", "city_tour", "casa_historica"],
    noIncluye: ["almuerzo", "cena", "traslados_aeropuerto"],
    fechaInicio: new Date("2026-07-09"),
    fechaFin: new Date("2026-07-11"),
    activo: true,
  },
  {
    nombre: "Mar del Plata Verano",
    descripcion: "Disfruta del verano en las playas de Mar del Plata",
    destino: "Mar del Plata",
    duracion: 7,
    noches: 6,
    precio: 68000,
    cupoMaximo: 30,
    cupoDisponible: 30,
    incluye: ["hotel", "desayuno", "sombrilla_playa"],
    noIncluye: ["almuerzo", "cena", "traslados_aeropuerto"],
    fechaInicio: new Date("2026-01-15"),
    fechaFin: new Date("2026-01-21"),
    activo: true,
  },
  {
    nombre: "Ruta de la Selva",
    descripcion: "Explora la selva misionera y sus maravillas naturales",
    destino: "Misiones",
    duracion: 6,
    noches: 5,
    precio: 72000,
    cupoMaximo: 16,
    cupoDisponible: 16,
    incluye: [
      "hotel",
      "desayuno",
      "cataratas",
      "saltos_mocona",
      "ruinas_jesuitas",
    ],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-04-20"),
    fechaFin: new Date("2026-04-25"),
    activo: true,
  },
  {
    nombre: "San Juan Aventura",
    descripcion: "Descubre los paisajes únicos de San Juan",
    destino: "San Juan",
    duracion: 5,
    noches: 4,
    precio: 62000,
    cupoMaximo: 15,
    cupoDisponible: 15,
    incluye: ["hotel", "desayuno", "ischigualasto", "dique_ullum", "traslados"],
    noIncluye: ["almuerzo", "cena"],
    fechaInicio: new Date("2026-08-10"),
    fechaFin: new Date("2026-08-14"),
    activo: true,
  },
  {
    nombre: "Rosario Cultural",
    descripcion: "Conoce la ciudad de Rosario y su cultura",
    destino: "Rosario",
    duracion: 3,
    noches: 2,
    precio: 38000,
    cupoMaximo: 25,
    cupoDisponible: 25,
    incluye: ["hotel", "desayuno", "city_tour", "monumento_bandera"],
    noIncluye: ["almuerzo", "cena", "traslados_aeropuerto"],
    fechaInicio: new Date("2026-05-22"),
    fechaFin: new Date("2026-05-24"),
    activo: true,
  },
  {
    nombre: "El Chaltén Trekking",
    descripcion: "Capital del trekking en Argentina",
    destino: "El Chaltén",
    duracion: 6,
    noches: 5,
    precio: 125000,
    cupoMaximo: 12,
    cupoDisponible: 12,
    incluye: ["hotel", "desayuno", "guia_trekking", "laguna_torre", "fitz_roy"],
    noIncluye: ["almuerzo", "cena", "equipo_trekking"],
    fechaInicio: new Date("2026-11-05"),
    fechaFin: new Date("2026-11-10"),
    activo: true,
  },
];

export const seedPaquetes = async () => {
  try {
    const count = await Paquete.count();
    if (count > 0) {
      console.log("⏭️  Paquetes ya existen en la base de datos. Saltando...");
      return;
    }

    // Agregar published_by_user_id a todos los paquetes
    const paquetesWithPublisher = paquetesData.map(paquete => ({
      ...paquete,
      published_by_user_id: 1 // Usuario admin/agencia
    }));

    await Paquete.bulkCreate(paquetesWithPublisher);
    console.log("✅ Paquetes creados exitosamente");
  } catch (error) {
    console.error("❌ Error al crear paquetes:", error.message);
    throw error;
  }
};
