import SalidaGrupal from "../models/SalidaGrupal.model.js";

const salidasGrupalesData = [
  {
    nombre: "Salida Grupal Bariloche Invierno",
    descripcion:
      "Viaje grupal a Bariloche para disfrutar de la nieve y actividades invernales",
    destino: "San Carlos de Bariloche",
    fechaSalida: new Date("2026-07-15"),
    fechaRegreso: new Date("2026-07-22"),
    duracion: 7,
    precio: 125000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "pase_ski",
      "excursion_circuito_chico",
    ],
    noIncluye: ["almuerzo", "cena", "equipo_ski", "clases"],
    itinerario: [
      "Día 1: Viaje y llegada",
      "Días 2-5: Esquí y actividades",
      "Día 6: Excursión circuito chico",
      "Día 7: Regreso",
    ],
    cupoMinimo: 15,
    cupoMaximo: 25,
    cupoDisponible: 25,
    acompañante: "Coordinador turístico especializado",
    activo: true,
  },
  {
    nombre: "Salida Grupal Mendoza Vendimia",
    descripcion:
      "Vive la Fiesta Nacional de la Vendimia en Mendoza con grupo de jóvenes",
    destino: "Mendoza",
    fechaSalida: new Date("2026-03-05"),
    fechaRegreso: new Date("2026-03-10"),
    duracion: 5,
    precio: 85000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "entrada_fiesta_vendimia",
      "tour_bodegas",
    ],
    noIncluye: ["almuerzo", "cena", "bebidas_extras"],
    itinerario: [
      "Día 1: Llegada y city tour",
      "Día 2: Tour de bodegas",
      "Día 3: Fiesta de la Vendimia",
      "Día 4: Alta montaña",
      "Día 5: Regreso",
    ],
    cupoMinimo: 20,
    cupoMaximo: 35,
    cupoDisponible: 35,
    acompañante: "Guía especializado en enología",
    activo: true,
  },
  {
    nombre: "Salida Grupal Iguazú Aventura",
    descripcion:
      "Aventura juvenil a las Cataratas del Iguazú con actividades extremas",
    destino: "Puerto Iguazú",
    fechaSalida: new Date("2026-06-10"),
    fechaRegreso: new Date("2026-06-14"),
    duracion: 4,
    precio: 72000,
    incluye: [
      "hostel",
      "desayuno",
      "traslados",
      "entrada_cataratas",
      "gran_aventura",
    ],
    noIncluye: ["almuerzo", "cena", "actividades_opcionales"],
    itinerario: [
      "Día 1: Llegada y noche de integración",
      "Día 2: Cataratas lado argentino",
      "Día 3: Gran Aventura y lado brasileño",
      "Día 4: Regreso",
    ],
    cupoMinimo: 18,
    cupoMaximo: 30,
    cupoDisponible: 30,
    acompañante: "Coordinador de turismo aventura",
    activo: true,
  },
  {
    nombre: "Salida Grupal Egresados Bariloche",
    descripcion:
      "Viaje de egresados clásico a Bariloche con todas las actividades",
    destino: "San Carlos de Bariloche",
    fechaSalida: new Date("2026-09-20"),
    fechaRegreso: new Date("2026-09-27"),
    duracion: 7,
    precio: 145000,
    incluye: [
      "hotel",
      "pension_completa",
      "traslados",
      "excursiones",
      "fiestas",
      "seguro",
    ],
    noIncluye: ["bebidas_alcoholicas", "actividades_opcionales"],
    itinerario: [
      "Día 1: Viaje y llegada",
      "Días 2-6: Excursiones y fiestas temáticas",
      "Día 7: Regreso",
    ],
    cupoMinimo: 40,
    cupoMaximo: 80,
    cupoDisponible: 80,
    acompañante: "Equipo de coordinadores especializados",
    activo: true,
  },
  {
    nombre: "Salida Grupal Salta Cultural",
    descripcion: "Descubre el norte argentino en grupo con guía cultural",
    destino: "Salta y Jujuy",
    fechaSalida: new Date("2026-05-15"),
    fechaRegreso: new Date("2026-05-22"),
    duracion: 7,
    precio: 98000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "guia_historico",
      "entradas",
    ],
    noIncluye: ["almuerzo", "cena"],
    itinerario: [
      "Días 1-3: Salta ciudad y alrededores",
      "Días 4-6: Quebrada de Humahuaca y Salinas Grandes",
      "Día 7: Regreso",
    ],
    cupoMinimo: 15,
    cupoMaximo: 25,
    cupoDisponible: 25,
    acompañante: "Guía cultural especializado",
    activo: true,
  },
  {
    nombre: "Salida Grupal Patagonia Express",
    descripcion: "Recorrido rápido por los highlights de la Patagonia",
    destino: "El Calafate y El Chaltén",
    fechaSalida: new Date("2026-11-10"),
    fechaRegreso: new Date("2026-11-17"),
    duracion: 7,
    precio: 195000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "entrada_glaciar",
    ],
    noIncluye: ["almuerzo", "cena", "trekking_glaciar"],
    itinerario: [
      "Días 1-4: El Calafate y glaciares",
      "Días 5-6: El Chaltén trekking",
      "Día 7: Regreso",
    ],
    cupoMinimo: 12,
    cupoMaximo: 20,
    cupoDisponible: 20,
    acompañante: "Guía de montaña certificado",
    activo: true,
  },
  {
    nombre: "Salida Grupal Ushuaia Fin del Mundo",
    descripcion: "Aventura al fin del mundo en grupo selecto",
    destino: "Ushuaia",
    fechaSalida: new Date("2026-12-15"),
    fechaRegreso: new Date("2026-12-20"),
    duracion: 5,
    precio: 158000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "navegacion_beagle",
      "parque_nacional",
      "tren_fin_mundo",
    ],
    noIncluye: ["almuerzo", "cena", "actividades_opcionales"],
    itinerario: [
      "Día 1: Llegada y city tour",
      "Día 2: Navegación Beagle",
      "Día 3: Parque Nacional y Tren",
      "Día 4: Lagos fueguinos",
      "Día 5: Regreso",
    ],
    cupoMinimo: 10,
    cupoMaximo: 18,
    cupoDisponible: 18,
    acompañante: "Coordinador especializado en Patagonia",
    activo: true,
  },
  {
    nombre: "Salida Grupal Córdoba Joven",
    descripcion:
      "Viaje juvenil a las sierras de Córdoba con actividades recreativas",
    destino: "Villa Carlos Paz",
    fechaSalida: new Date("2026-02-10"),
    fechaRegreso: new Date("2026-02-15"),
    duracion: 5,
    precio: 58000,
    incluye: ["hotel", "desayuno", "traslados", "excursiones", "actividades"],
    noIncluye: ["almuerzo", "cena", "discotecas"],
    itinerario: [
      "Día 1: Llegada y noche de bienvenida",
      "Días 2-4: Excursiones y recreación",
      "Día 5: Regreso",
    ],
    cupoMinimo: 25,
    cupoMaximo: 40,
    cupoDisponible: 40,
    acompañante: "Equipo de recreación",
    activo: true,
  },
  {
    nombre: "Salida Grupal Brasil Playas",
    descripcion:
      "Viaje grupal a las playas de Brasil: Camboriú, Florianópolis y más",
    destino: "Santa Catarina, Brasil",
    fechaSalida: new Date("2026-01-20"),
    fechaRegreso: new Date("2026-01-28"),
    duracion: 8,
    precio: 165000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "fiestas",
      "seguro",
    ],
    noIncluye: ["almuerzo", "cena", "pasaporte", "bebidas"],
    itinerario: [
      "Días 1-4: Balneario Camboriú",
      "Días 5-7: Florianópolis",
      "Día 8: Regreso",
    ],
    cupoMinimo: 30,
    cupoMaximo: 50,
    cupoDisponible: 50,
    acompañante: "Coordinador bilingüe",
    activo: true,
  },
  {
    nombre: "Salida Grupal Termas Relax",
    descripcion: "Escapada de relax grupal a las termas de Entre Ríos",
    destino: "Federación, Entre Ríos",
    fechaSalida: new Date("2026-08-20"),
    fechaRegreso: new Date("2026-08-24"),
    duracion: 4,
    precio: 52000,
    incluye: [
      "hotel_termal",
      "desayuno",
      "acceso_ilimitado_termas",
      "traslados",
    ],
    noIncluye: ["almuerzo", "cena", "masajes", "tratamientos"],
    itinerario: [
      "Día 1: Viaje y llegada",
      "Días 2-3: Termas y relax",
      "Día 4: Regreso",
    ],
    cupoMinimo: 15,
    cupoMaximo: 25,
    cupoDisponible: 25,
    acompañante: "Coordinador wellness",
    activo: true,
  },
  {
    nombre: "Salida Grupal Carnaval Gualeguaychú",
    descripcion: "Vive el carnaval más largo del mundo en Gualeguaychú",
    destino: "Gualeguaychú, Entre Ríos",
    fechaSalida: new Date("2026-02-21"),
    fechaRegreso: new Date("2026-02-23"),
    duracion: 2,
    precio: 38000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "entrada_carnaval",
      "cena_show",
    ],
    noIncluye: ["almuerzo", "bebidas"],
    itinerario: ["Día 1: Viaje, llegada y carnaval", "Día 2: Regreso"],
    cupoMinimo: 20,
    cupoMaximo: 40,
    cupoDisponible: 40,
    acompañante: "Coordinador de eventos",
    activo: true,
  },
  {
    nombre: "Salida Grupal Península Valdés",
    descripcion: "Avistaje de ballenas y fauna marina en grupo especializado",
    destino: "Puerto Madryn",
    fechaSalida: new Date("2026-09-25"),
    fechaRegreso: new Date("2026-09-30"),
    duracion: 5,
    precio: 115000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "avistaje_ballenas",
      "peninsula_valdes",
      "pinguinera",
    ],
    noIncluye: ["almuerzo", "cena", "navegaciones_adicionales"],
    itinerario: [
      "Día 1: Llegada",
      "Día 2: Avistaje de ballenas",
      "Día 3: Península Valdés",
      "Día 4: Punta Tombo",
      "Día 5: Regreso",
    ],
    cupoMinimo: 12,
    cupoMaximo: 20,
    cupoDisponible: 20,
    acompañante: "Biólogo guía especializado",
    activo: true,
  },
  {
    nombre: "Salida Grupal San Martín de los Andes",
    descripcion: "Descubre la perla de la Patagonia en grupo",
    destino: "San Martín de los Andes",
    fechaSalida: new Date("2026-03-15"),
    fechaRegreso: new Date("2026-03-20"),
    duracion: 5,
    precio: 95000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "excursiones",
      "ruta_siete_lagos",
    ],
    noIncluye: ["almuerzo", "cena", "actividades_opcionales"],
    itinerario: [
      "Día 1: Llegada y city tour",
      "Día 2: Ruta de los Siete Lagos",
      "Día 3: Volcán Lanín",
      "Día 4: Lago Lácar",
      "Día 5: Regreso",
    ],
    cupoMinimo: 15,
    cupoMaximo: 25,
    cupoDisponible: 25,
    acompañante: "Guía de turismo regional",
    activo: true,
  },
  {
    nombre: "Salida Grupal Trekking Fitz Roy",
    descripcion: "Aventura de trekking al Fitz Roy para montañistas",
    destino: "El Chaltén",
    fechaSalida: new Date("2026-11-20"),
    fechaRegreso: new Date("2026-11-26"),
    duracion: 6,
    precio: 135000,
    incluye: [
      "hospedaje",
      "desayuno",
      "traslados",
      "guia_montaña",
      "viandas_trekking",
    ],
    noIncluye: ["equipo_trekking", "cenas", "seguro_montaña"],
    itinerario: [
      "Día 1: Llegada y preparativos",
      "Día 2: Trekking Laguna de los Tres",
      "Día 3: Trekking Laguna Torre",
      "Día 4: Loma del Pliegue Tumbado",
      "Día 5: Descanso",
      "Día 6: Regreso",
    ],
    cupoMinimo: 8,
    cupoMaximo: 15,
    cupoDisponible: 15,
    acompañante: "Guía de alta montaña",
    activo: true,
  },
  {
    nombre: "Salida Grupal Oktoberfest Villa General Belgrano",
    descripcion: "Vive la fiesta de la cerveza en las sierras cordobesas",
    destino: "Villa General Belgrano, Córdoba",
    fechaSalida: new Date("2026-10-09"),
    fechaRegreso: new Date("2026-10-12"),
    duracion: 3,
    precio: 45000,
    incluye: [
      "hotel",
      "desayuno",
      "traslados",
      "entrada_oktoberfest",
      "degustacion_cerveza",
    ],
    noIncluye: ["almuerzo", "cena", "consumiciones_extras"],
    itinerario: [
      "Día 1: Viaje y llegada, noche Oktoberfest",
      "Día 2: Día completo Oktoberfest",
      "Día 3: Regreso",
    ],
    cupoMinimo: 20,
    cupoMaximo: 35,
    cupoDisponible: 35,
    acompañante: "Coordinador de eventos",
    activo: true,
  },
];

export const seedSalidasGrupales = async () => {
  try {
    const count = await SalidaGrupal.count();
    if (count > 0) {
      console.log(
        "⏭️  Salidas grupales ya existen en la base de datos. Saltando..."
      );
      return;
    }

    const salidasWithPublisher = salidasGrupalesData.map(salida => ({
      ...salida,
      published_by_user_id: 1
    }));

    await SalidaGrupal.bulkCreate(salidasWithPublisher);
    console.log("✅ Salidas grupales creadas exitosamente");
  } catch (error) {
    console.error("❌ Error al crear salidas grupales:", error.message);
    throw error;
  }
};
