const Seguro = require("../models/Seguro.model");
const { getSeedImages } = require("./seedImages");

const baseSeguros = [
  {
    nombre: "Seguro Viajero Básico",
    aseguradora: "Assist Card",
    tipo: "viaje",
    descripcion: "Cobertura básica para viajes cortos dentro de Argentina",
    cobertura: [
      "asistencia_medica",
      "medicamentos",
      "odontologia_urgencia",
      "traslados",
    ],
    montoCobertura: 30000,
    precio: 1500,
    duracionMaxima: 15,
    edadMinima: 0,
    edadMaxima: 70,
    destinosIncluidos: ["Argentina"],
    exclusiones: ["deportes_extremos", "preexistencias"],
    disponible: true,
  },
  {
    nombre: "Seguro Viajero Premium",
    aseguradora: "Assist Card",
    tipo: "integral",
    descripcion: "Cobertura completa para viajes internacionales",
    cobertura: [
      "asistencia_medica",
      "medicamentos",
      "hospitalizacion",
      "odontologia",
      "traslados",
      "repatriacion",
      "equipaje",
      "cancelacion",
    ],
    montoCobertura: 100000,
    precio: 8500,
    duracionMaxima: 60,
    edadMinima: 0,
    edadMaxima: 85,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["deportes_extremos", "guerra"],
    disponible: true,
  },
  {
    nombre: "Seguro Médico Internacional",
    aseguradora: "Universal Assistance",
    tipo: "medico",
    descripcion: "Cobertura médica para viajes al exterior",
    cobertura: [
      "asistencia_medica",
      "medicamentos",
      "hospitalizacion",
      "cirugias",
      "traslados_sanitarios",
    ],
    montoCobertura: 50000,
    precio: 4200,
    duracionMaxima: 30,
    edadMinima: 0,
    edadMaxima: 75,
    destinosIncluidos: ["America", "Europa"],
    exclusiones: ["enfermedades_cronicas", "embarazo"],
    disponible: true,
  },
  {
    nombre: "Seguro Cancelación de Viaje",
    aseguradora: "Travel Ace",
    tipo: "cancelacion",
    descripcion: "Reembolso por cancelación de viaje por causas cubiertas",
    cobertura: [
      "cancelacion_enfermedad",
      "cancelacion_fallecimiento",
      "interrupcion_viaje",
      "demora_vuelo",
    ],
    montoCobertura: 150000,
    precio: 5500,
    duracionMaxima: 45,
    edadMinima: 18,
    edadMaxima: 80,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["cambio_opinion", "problemas_proveedor"],
    disponible: true,
  },
  {
    nombre: "Seguro Equipaje",
    aseguradora: "Coris",
    tipo: "equipaje",
    descripcion: "Cobertura por pérdida, robo o daño de equipaje",
    cobertura: [
      "perdida_equipaje",
      "robo_equipaje",
      "daño_equipaje",
      "demora_equipaje",
    ],
    montoCobertura: 20000,
    precio: 1200,
    duracionMaxima: 30,
    edadMinima: 0,
    edadMaxima: 99,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["objetos_valor_alto", "electronica_sin_declarar"],
    disponible: true,
  },
  {
    nombre: "Seguro Asistencia al Viajero Europa",
    aseguradora: "Assist 365",
    tipo: "asistencia",
    descripcion: "Asistencia integral cumple requisitos Schengen",
    cobertura: [
      "asistencia_medica",
      "hospitalizacion",
      "medicamentos",
      "repatriacion",
      "traslados",
      "asistencia_legal",
    ],
    montoCobertura: 60000,
    precio: 6800,
    duracionMaxima: 90,
    edadMinima: 0,
    edadMaxima: 85,
    destinosIncluidos: ["Europa"],
    exclusiones: ["deportes_riesgo"],
    disponible: true,
  },
  {
    nombre: "Seguro Cruceros",
    aseguradora: "Universal Assistance",
    tipo: "viaje",
    descripcion: "Seguro especial para viajes en crucero",
    cobertura: [
      "asistencia_medica_bordo",
      "evacuacion_medica",
      "interrupcion_crucero",
      "perdida_conexion",
    ],
    montoCobertura: 75000,
    precio: 12000,
    duracionMaxima: 30,
    edadMinima: 0,
    edadMaxima: 80,
    destinosIncluidos: ["Mundial_maritimo"],
    exclusiones: ["deportes_extremos", "embarazo_avanzado"],
    disponible: true,
  },
  {
    nombre: "Seguro Estudiante",
    aseguradora: "Assist Card",
    tipo: "integral",
    descripcion: "Cobertura especial para estudiantes en el exterior",
    cobertura: [
      "asistencia_medica",
      "medicamentos",
      "hospitalizacion",
      "repatriacion",
      "responsabilidad_civil",
      "equipaje",
    ],
    montoCobertura: 45000,
    precio: 3500,
    duracionMaxima: 365,
    edadMinima: 16,
    edadMaxima: 35,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["deportes_profesionales"],
    disponible: true,
  },
  {
    nombre: "Seguro Deportes Aventura",
    aseguradora: "Travel Ace",
    tipo: "viaje",
    descripcion: "Cobertura para viajes con actividades de aventura",
    cobertura: [
      "asistencia_medica",
      "hospitalizacion",
      "rescate_montaña",
      "deportes_aventura",
      "evacuacion_helicoptero",
    ],
    montoCobertura: 80000,
    precio: 15000,
    duracionMaxima: 21,
    edadMinima: 18,
    edadMaxima: 65,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["deportes_extremos_profesionales"],
    disponible: true,
  },
  {
    nombre: "Seguro Familiar",
    aseguradora: "Coris",
    tipo: "integral",
    descripcion: "Cobertura para toda la familia hasta 5 personas",
    cobertura: [
      "asistencia_medica",
      "medicamentos",
      "hospitalizacion",
      "traslados",
      "repatriacion",
      "equipaje",
    ],
    montoCobertura: 60000,
    precio: 18000,
    duracionMaxima: 30,
    edadMinima: 0,
    edadMaxima: 99,
    destinosIncluidos: ["America"],
    exclusiones: ["deportes_riesgo"],
    disponible: true,
  },
  {
    nombre: "Seguro COVID-19",
    aseguradora: "Assist 365",
    tipo: "medico",
    descripcion: "Cobertura específica para COVID-19 durante el viaje",
    cobertura: [
      "asistencia_covid",
      "hospitalizacion_covid",
      "cuarentena_obligatoria",
      "pcr_destino",
      "medicamentos_covid",
    ],
    montoCobertura: 40000,
    precio: 3800,
    duracionMaxima: 60,
    edadMinima: 0,
    edadMaxima: 85,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["sin_vacunacion"],
    disponible: true,
  },
  {
    nombre: "Seguro Anual Multiviaje",
    aseguradora: "Universal Assistance",
    tipo: "integral",
    descripcion: "Cobertura anual para viajes múltiples",
    cobertura: [
      "asistencia_medica",
      "hospitalizacion",
      "medicamentos",
      "repatriacion",
      "equipaje",
      "cancelacion",
    ],
    montoCobertura: 50000,
    precio: 45000,
    duracionMaxima: 365,
    edadMinima: 18,
    edadMaxima: 70,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["viajes_mayores_60dias"],
    disponible: true,
  },
  {
    nombre: "Seguro Tercera Edad",
    aseguradora: "Assist Card",
    tipo: "medico",
    descripcion: "Seguro especial para mayores de 70 años",
    cobertura: [
      "asistencia_medica",
      "hospitalizacion",
      "medicamentos",
      "traslados",
      "acompañante",
    ],
    montoCobertura: 55000,
    precio: 9500,
    duracionMaxima: 30,
    edadMinima: 70,
    edadMaxima: 85,
    destinosIncluidos: ["America"],
    exclusiones: ["enfermedades_preexistentes"],
    disponible: true,
  },
  {
    nombre: "Seguro Business Travel",
    aseguradora: "Travel Ace",
    tipo: "viaje",
    descripcion: "Cobertura para viajes de negocios frecuentes",
    cobertura: [
      "asistencia_medica",
      "hospitalizacion",
      "equipaje_negocios",
      "documentos",
      "responsabilidad_civil",
      "asistencia_legal",
    ],
    montoCobertura: 70000,
    precio: 7200,
    duracionMaxima: 90,
    edadMinima: 18,
    edadMaxima: 75,
    destinosIncluidos: ["Mundial"],
    exclusiones: ["viajes_recreativos"],
    disponible: true,
  },
  {
    nombre: "Seguro Mochilero",
    aseguradora: "Assist 365",
    tipo: "viaje",
    descripcion: "Seguro económico para viajeros mochileros",
    cobertura: [
      "asistencia_medica",
      "medicamentos",
      "hospitalizacion_basica",
      "traslados",
    ],
    montoCobertura: 25000,
    precio: 2200,
    duracionMaxima: 180,
    edadMinima: 18,
    edadMaxima: 45,
    destinosIncluidos: ["America"],
    exclusiones: ["deportes_riesgo", "enfermedades_cronicas"],
    disponible: true,
  },
];

const segurosData = baseSeguros.map((seguro, index) => ({
  ...seguro,
  imagenes: getSeedImages(index, 3),
  destacado: index < 2,
}));

const seedSeguros = async () => {
  try {
    const count = await Seguro.count();
    if (count > 0) {
      console.log("⏭️  Seguros ya existen en la base de datos. Saltando...");
      return;
    }

    await Seguro.bulkCreate(segurosData);
    console.log("✅ Seguros creados exitosamente");
  } catch (error) {
    console.error("❌ Error al crear seguros:", error.message);
    throw error;
  }
};


module.exports = {
  seedSeguros
};
