const Transfer = require("../models/Transfer.model");

const transfersData = [
  {
    tipo: "aeropuerto-hotel",
    origen: "Aeropuerto Ezeiza",
    destino: "Hotel Centro Buenos Aires",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 12000,
    duracionEstimada: 60,
    servicioCompartido: false,
    descripcion: "Transfer privado desde Ezeiza al centro de Buenos Aires",
    incluye: ["conductor", "wifi", "agua"],
    disponible: true,
  },
  {
    tipo: "hotel-aeropuerto",
    origen: "Hotel Palermo",
    destino: "Aeropuerto Aeroparque",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 8000,
    duracionEstimada: 30,
    servicioCompartido: false,
    descripcion: "Transfer privado desde Palermo a Aeroparque",
    incluye: ["conductor", "wifi"],
    disponible: true,
  },
  {
    tipo: "aeropuerto-hotel",
    origen: "Aeropuerto Bariloche",
    destino: "Hotel Centro Bariloche",
    vehiculo: "van",
    capacidadPasajeros: 7,
    precio: 15000,
    duracionEstimada: 25,
    servicioCompartido: true,
    descripcion: "Transfer compartido desde aeropuerto a hoteles en Bariloche",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "interhotel",
    origen: "Hotel Recoleta",
    destino: "Hotel Puerto Madero",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 5000,
    duracionEstimada: 20,
    servicioCompartido: false,
    descripcion: "Transfer entre hoteles en Buenos Aires",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "punto-a-punto",
    origen: "Terminal Retiro",
    destino: "Colonia del Sacramento (Ferry)",
    vehiculo: "minibus",
    capacidadPasajeros: 15,
    precio: 8000,
    duracionEstimada: 45,
    servicioCompartido: true,
    descripcion: "Transfer compartido a la terminal de Ferry a Colonia",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "aeropuerto-hotel",
    origen: "Aeropuerto Iguazú",
    destino: "Hotel Zona Cataratas",
    vehiculo: "van",
    capacidadPasajeros: 6,
    precio: 9000,
    duracionEstimada: 35,
    servicioCompartido: false,
    descripcion: "Transfer privado desde aeropuerto a hoteles zona cataratas",
    incluye: ["conductor", "wifi"],
    disponible: true,
  },
  {
    tipo: "hotel-aeropuerto",
    origen: "Hotel Mendoza Centro",
    destino: "Aeropuerto Mendoza",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 7500,
    duracionEstimada: 25,
    servicioCompartido: false,
    descripcion: "Transfer privado desde hotel al aeropuerto de Mendoza",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "aeropuerto-hotel",
    origen: "Aeropuerto Salta",
    destino: "Hotel Centro Salta",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 6500,
    duracionEstimada: 20,
    servicioCompartido: false,
    descripcion: "Transfer privado desde aeropuerto al centro de Salta",
    incluye: ["conductor", "agua"],
    disponible: true,
  },
  {
    tipo: "punto-a-punto",
    origen: "Buenos Aires",
    destino: "Tigre Delta",
    vehiculo: "van",
    capacidadPasajeros: 8,
    precio: 18000,
    duracionEstimada: 50,
    servicioCompartido: false,
    descripcion: "Transfer privado desde Buenos Aires al Delta de Tigre",
    incluye: ["conductor", "wifi"],
    disponible: true,
  },
  {
    tipo: "aeropuerto-hotel",
    origen: "Aeropuerto El Calafate",
    destino: "Hotel El Calafate",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 8500,
    duracionEstimada: 30,
    servicioCompartido: false,
    descripcion: "Transfer privado desde aeropuerto a hotel en El Calafate",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "hotel-aeropuerto",
    origen: "Hotel Ushuaia",
    destino: "Aeropuerto Ushuaia",
    vehiculo: "van",
    capacidadPasajeros: 6,
    precio: 9500,
    duracionEstimada: 15,
    servicioCompartido: true,
    descripcion: "Transfer compartido desde hoteles al aeropuerto de Ushuaia",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "punto-a-punto",
    origen: "Córdoba Centro",
    destino: "Villa Carlos Paz",
    vehiculo: "minibus",
    capacidadPasajeros: 12,
    precio: 12000,
    duracionEstimada: 45,
    servicioCompartido: true,
    descripcion: "Transfer compartido desde Córdoba a Villa Carlos Paz",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "aeropuerto-hotel",
    origen: "Aeropuerto Ezeiza",
    destino: "Hotel Zona Norte",
    vehiculo: "bus",
    capacidadPasajeros: 30,
    precio: 6000,
    duracionEstimada: 90,
    servicioCompartido: true,
    descripcion: "Transfer compartido económico desde Ezeiza a zona norte",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "interhotel",
    origen: "Hotel San Telmo",
    destino: "Hotel Microcentro",
    vehiculo: "sedan",
    capacidadPasajeros: 3,
    precio: 4500,
    duracionEstimada: 15,
    servicioCompartido: false,
    descripcion: "Transfer corto entre hoteles céntricos",
    incluye: ["conductor"],
    disponible: true,
  },
  {
    tipo: "punto-a-punto",
    origen: "Hotel Puerto Madryn",
    destino: "Península Valdés",
    vehiculo: "van",
    capacidadPasajeros: 8,
    precio: 25000,
    duracionEstimada: 90,
    servicioCompartido: false,
    descripcion: "Transfer privado para tour a Península Valdés",
    incluye: ["conductor", "wifi"],
    disponible: true,
  },
];

const seedTransfers = async () => {
  try {
    const count = await Transfer.count();
    if (count > 0) {
      console.log("⏭️  Transfers ya existen en la base de datos. Saltando...");
      return;
    }

    await Transfer.bulkCreate(transfersData);
    console.log("✅ Transfers creados exitosamente");
  } catch (error) {
    console.error("❌ Error al crear transfers:", error.message);
    throw error;
  }
};

module.exports = { seedTransfers };
